# Generated by Django 4.2.16 on 2024-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100)),
                ('login_url', models.CharField(max_length=200)),
                ('login_id', models.CharField(max_length=150)),
                ('login_pw', models.CharField(max_length=150)),
            ],
        ),
    ]
